version: '3'
services: 
    app:
        build:
            context: .
            dockerfile: ./docker/vue/Dockerfile
        volumes:
            - ./app:/app
            - /app/node_modules
        ports:
            - 8080:8080
        environment:
            - TZ=Asia/Tokyo
            - HOST=0.0.0.0
            - CHOKIDAR_USEPOLLING=true
        tty: true
        command: /start.sh
        # command: /bin/bash
